CREATE DATABASE IF NOT EXISTS QuizWebsite;

USE QuizWebsite;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    name VARCHAR(100) PRIMARY KEY,
    hashedpassword VARCHAR(255) NOT NULL,
    isadmin boolean NOT NULL
);

DROP TABLE IF EXISTS announcements;

CREATE TABLE announcements (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    text TEXT NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

