name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Java
        run: |
          cd Quiz-Website
          mvn clean install -DskipTests
  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run unit tests
        run: |
          cd Quiz-Website
          mvn test